In [1]:
import pdfplumber
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('D://test.xlsx')

In [3]:
df

  Transaction Date Memo  Amount  Debit  Credit
0       2026-04-20  abc     NaN    500     600
1       2026-04-22  def     NaN    400     300

In [4]:
column_mapping = {
 'Date': 'date',
 'Transaction Date': 'date',
 'Description': 'description',
 'Memo': 'description',
 'Amount': 'amount',
 'Debit': 'debit',
 'Credit': 'credit'
}
df.rename(columns=column_mapping, inplace=True)

In [5]:
df

        date description  amount  debit  credit
0 2026-04-20         abc     NaN    500     600
1 2026-04-22         def     NaN    400     300

In [6]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [7]:
df

        date description  amount  debit  credit
0 2026-04-20         abc     NaN    500     600
1 2026-04-22         def     NaN    400     300

In [8]:
if 'debit' in df.columns and 'credit' in df.columns:
    df['amount'] = df['credit'].fillna(0) - df['debit'].fillna(0)
    df.drop(['debit', 'credit'], axis=1, inplace=True)

In [9]:
df

        date description  amount
0 2026-04-20         abc     100
1 2026-04-22         def    -100

In [13]:
df['description'] = df['description'].str.strip().str.upper()

In [14]:
df

        date description  amount
0 2026-04-20         ABC     100
1 2026-04-22         DEF    -100

In [16]:
df = df.sort_values('date').reset_index(drop=True)

In [17]:
df

        date description  amount
0 2026-04-20         ABC     100
1 2026-04-22         DEF    -100