In [1]:
def create_categorization_rules():
    """
    Define rules for automatic transaction categorization
    """
    rules = {
        'Office Supplies': ['STAPLES', 'OFFICE DEPOT', 'AMAZON'],
        'Utilities': ['ELECTRIC', 'GAS COMPANY', 'WATER', 'INTERNET'],
        'Marketing': ['GOOGLE ADS', 'FACEBOOK', 'LINKEDIN', 'MAILCHIMP'],
        'Software': ['MICROSOFT', 'ADOBE', 'DROPBOX', 'SLACK'],
        'Meals & Entertainment': ['RESTAURANT', 'COFFEE', 'STARBUCKS', 'LUNCH'],
        'Travel': ['AIRLINE', 'HOTEL', 'UBER', 'LYFT', 'RENTAL CAR'],
        'Professional Services': ['LEGAL', 'ACCOUNTING', 'CONSULTING'],
        'Rent': ['LANDLORD', 'PROPERTY MANAGEMENT', 'RENT'],
        'Insurance': ['INSURANCE'],
        'Bank Fees': ['MONTHLY FEE', 'SERVICE CHARGE', 'ATM FEE'],
        'Client Payment': ['PAYMENT RECEIVED', 'INVOICE', 'DEPOSIT'],
        'Owner Draw': ['TRANSFER TO PERSONAL', 'OWNER WITHDRAWAL']
    }
    return rules

In [2]:
our_rules = create_categorization_rules()

In [3]:
our_rules

{'Office Supplies': ['STAPLES', 'OFFICE DEPOT', 'AMAZON'],
 'Utilities': ['ELECTRIC', 'GAS COMPANY', 'WATER', 'INTERNET'],
 'Marketing': ['GOOGLE ADS', 'FACEBOOK', 'LINKEDIN', 'MAILCHIMP'],
 'Software': ['MICROSOFT', 'ADOBE', 'DROPBOX', 'SLACK'],
 'Meals & Entertainment': ['RESTAURANT', 'COFFEE', 'STARBUCKS', 'LUNCH'],
 'Travel': ['AIRLINE', 'HOTEL', 'UBER', 'LYFT', 'RENTAL CAR'],
 'Professional Services': ['LEGAL', 'ACCOUNTING', 'CONSULTING'],
 'Rent': ['LANDLORD', 'PROPERTY MANAGEMENT', 'RENT'],
 'Insurance': ['INSURANCE'],
 'Bank Fees': ['MONTHLY FEE', 'SERVICE CHARGE', 'ATM FEE'],
 'Client Payment': ['PAYMENT RECEIVED', 'INVOICE', 'DEPOSIT'],
 'Owner Draw': ['TRANSFER TO PERSONAL', 'OWNER WITHDRAWAL']}

In [4]:
your_rules = {
        'Office Supplies': ['STAPLES', 'OFFICE DEPOT', 'AMAZON'],
        'Utilities': ['ELECTRIC', 'GAS COMPANY', 'WATER', 'INTERNET'],
        'Marketing': ['GOOGLE ADS', 'FACEBOOK', 'LINKEDIN', 'MAILCHIMP'],
        'Software': ['MICROSOFT', 'ADOBE', 'DROPBOX', 'SLACK'],
        'Meals & Entertainment': ['RESTAURANT', 'COFFEE', 'STARBUCKS', 'LUNCH'],
        'Travel': ['AIRLINE', 'HOTEL', 'UBER', 'LYFT', 'RENTAL CAR'],
        'Professional Services': ['LEGAL', 'ACCOUNTING', 'CONSULTING'],
        'Rent': ['LANDLORD', 'PROPERTY MANAGEMENT', 'RENT'],
        'Insurance': ['INSURANCE'],
        'Bank Fees': ['MONTHLY FEE', 'SERVICE CHARGE', 'ATM FEE'],
        'Client Payment': ['PAYMENT RECEIVED', 'INVOICE', 'DEPOSIT'],
        'Owner Draw': ['TRANSFER TO PERSONAL', 'OWNER WITHDRAWAL']
    }

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import pdfplumber

def import_bank_transactions(file_path, file_type='csv'):
    """
    Import transactions from various file formats
    """
    if file_type == 'csv':
        df = pd.read_csv(file_path)
    elif file_type == 'excel':
        df = pd.read_excel(file_path)
    elif file_type == 'pdf':
        df = extract_from_pdf(file_path)
    
    # Standardize column names
    column_mapping = {
        'Date': 'date',
        'Transaction Date': 'date',
        'Description': 'description',
        'Memo': 'description',
        'Amount': 'amount',
        'Debit': 'debit',
        'Credit': 'credit'
    }
    
    df.rename(columns=column_mapping, inplace=True)
    
    # Convert date to datetime
    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    
    # Combine debit/credit into single amount column if needed
    if 'debit' in df.columns and 'credit' in df.columns:
        df['amount'] = df['credit'].fillna(0) - df['debit'].fillna(0)
        df.drop(['debit', 'credit'], axis=1, inplace=True)
    
    # Clean description field
    df['description'] = df['description'].str.strip().str.upper()
    
    return df.sort_values('date').reset_index(drop=True)

In [2]:
def extract_from_pdf(pdf_path):
    """
    Extract transaction data from PDF bank statements
    """
    transactions = []
    
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            # Parse text based on your bank's format
            # This is a simplified example
            lines = text.split('\n')
            for line in lines:
                # Custom parsing logic for your bank's format
                parts = line.split()
                if len(parts) >= 3:
                    transactions.append({
                        'date': parts[0],
                        'description': ' '.join(parts[1:-1]),
                        'amount': parts[-1]
                    })
    
    return pd.DataFrame(transactions)

In [3]:
# Import transactions from multiple sources
bank_transactions = import_bank_transactions("C://Harman\sample_bank_transactions.xlsx", 'excel')

In [4]:
bank_transactions

        date                    description   amount
0 2024-01-05  STAPLES OFFICE SUPPLIES STORE   -45.99
1 2024-01-06                UBER TRIP 8X4K2   -18.50
2 2024-01-07          STARBUCKS STORE #4521    -6.75
3 2024-01-08  PAYMENT RECEIVED INVOICE 1023  1500.00
4 2024-01-10            GOOGLE ADS CAMPAIGN  -250.00
5 2024-01-12          ELECTRIC COMPANY BILL  -120.34
6 2024-01-15                    MONTHLY FEE   -12.00
7 2024-01-18  TRANSFER TO PERSONAL CHECKING  -800.00
8 2024-01-20          UNKNOWN VENDOR XYZ123   -99.99
9 2024-01-22          WIRE TRANSFER DEPOSIT  2200.00

In [14]:
def create_categorization_rules():
    """
    Define rules for automatic transaction categorization
    """
    rules = {
        'Office Supplies': ['STAPLES', 'OFFICE DEPOT', 'AMAZON'],
        'Utilities': ['ELECTRIC', 'GAS COMPANY', 'WATER', 'INTERNET'],
        'Marketing': ['GOOGLE ADS', 'FACEBOOK', 'LINKEDIN', 'MAILCHIMP'],
        'Software': ['MICROSOFT', 'ADOBE', 'DROPBOX', 'SLACK'],
        'Meals & Entertainment': ['RESTAURANT', 'COFFEE', 'STARBUCKS', 'LUNCH'],
        'Travel': ['AIRLINE', 'HOTEL', 'UBER', 'LYFT', 'RENTAL CAR'],
        'Professional Services': ['LEGAL', 'ACCOUNTING', 'CONSULTING'],
        'Rent': ['LANDLORD', 'PROPERTY MANAGEMENT', 'RENT'],
        'Insurance': ['INSURANCE'],
        'Bank Fees': ['MONTHLY FEE', 'SERVICE CHARGE', 'ATM FEE'],
        'Client Payment': ['PAYMENT RECEIVED', 'INVOICE', 'DEPOSIT'],
        'Owner Draw': ['TRANSFER TO PERSONAL', 'OWNER WITHDRAWAL']
    }
    return rules

### A better approach

Instead of always assigning 0.9, you could vary the **confidence** based on the strength of the match.

For example:

if exact_match:

    confidence = 1.0
    
elif keyword_match:

    confidence = 0.9
    
elif partial_match:

    confidence = 0.7
    
else:

    confidence = 0.5

In [15]:
def categorize_transactions(df, rules):
    """
    Automatically categorize transactions based on description
    """
    df['category'] = 'Uncategorized'
    df['confidence'] = 0.0
    
    for category, keywords in rules.items():
        for keyword in keywords:
            mask = df['description'].str.contains(keyword, case=False, na=False)
            # Only categorize if not already categorized
            uncategorized = df['category'] == 'Uncategorized'
            df.loc[mask & uncategorized, 'category'] = category
            df.loc[mask & uncategorized, 'confidence'] = 0.9
    
    # Categorize by amount patterns
    df.loc[(df['amount'] > 0) & (df['category'] == 'Uncategorized'), 'category'] = 'Income'
    df.loc[(df['amount'] < 0) & (df['category'] == 'Uncategorized'), 'category'] = 'Other Expense'
    
    return df

In [16]:
b = create_categorization_rules()
a = categorize_transactions(bank_transactions, b)

In [17]:
a.head()

,date,description,amount,category,confidence
0,2024-01-05,STAPLES OFFICE SUPPLIES STORE,-45.99,Office Supplies,0.9
1,2024-01-06,UBER TRIP 8X4K2,-18.50,Travel,0.9
2,2024-01-07,STARBUCKS STORE #4521,-6.75,Meals & Entertainment,0.9
3,2024-01-08,PAYMENT RECEIVED INVOICE 1023,1500.00,Client Payment,0.9
4,2024-01-10,GOOGLE ADS CAMPAIGN,-250.00,Marketing,0.9

In [10]:
def learn_from_manual_categories(df, manual_categories_file='C://Harman\manual_categories.csv'):
    """
    Learn from previously manually categorized transactions
    """
    try:
        manual = pd.read_csv(manual_categories_file)
        
        # Create a mapping of descriptions to categories
        category_map = {}   # -> {"UBER TRIP": "TRaVEL"}
        for i, row in manual.iterrows():
            category_map[row['description']] = row['category']
            
        # Apply learned categories
        for desc, cat in category_map.items():
            mask = df['description'] == desc
            df.loc[mask, 'category'] = cat
            df.loc[mask, 'confidence'] = 1.0
    except FileNotFoundError:
        print("No manual categorization history found")
    
    return df

In [18]:
c = learn_from_manual_categories(bank_transactions)

In [19]:
c.head()

,date,description,amount,category,confidence
0,2024-01-05,STAPLES OFFICE SUPPLIES STORE,-45.99,Office Supplies,0.9
1,2024-01-06,UBER TRIP 8X4K2,-18.50,Travel,1.0
2,2024-01-07,STARBUCKS STORE #4521,-6.75,Meals & Entertainment,1.0
3,2024-01-08,PAYMENT RECEIVED INVOICE 1023,1500.00,Client Payment,0.9
4,2024-01-10,GOOGLE ADS CAMPAIGN,-250.00,Marketing,1.0

In [16]:
bank_transactions['category'] = 'Uncategorized'
bank_transactions['confidence'] = 0.0

In [17]:
bank_transactions

        date description  amount       category  confidence
0 2026-04-20         ABC     100  Uncategorized         0.0
1 2026-04-22         DEF    -100  Uncategorized         0.0

In [18]:
our_rules

{'Office Supplies': ['STAPLES', 'OFFICE DEPOT', 'AMAZON'],
 'Utilities': ['ELECTRIC', 'GAS COMPANY', 'WATER', 'INTERNET'],
 'Marketing': ['GOOGLE ADS', 'FACEBOOK', 'LINKEDIN', 'MAILCHIMP'],
 'Software': ['MICROSOFT', 'ADOBE', 'DROPBOX', 'SLACK'],
 'Meals & Entertainment': ['RESTAURANT', 'COFFEE', 'STARBUCKS', 'LUNCH'],
 'Travel': ['AIRLINE', 'HOTEL', 'UBER', 'LYFT', 'RENTAL CAR'],
 'Professional Services': ['LEGAL', 'ACCOUNTING', 'CONSULTING'],
 'Rent': ['LANDLORD', 'PROPERTY MANAGEMENT', 'RENT'],
 'Insurance': ['INSURANCE'],
 'Bank Fees': ['MONTHLY FEE', 'SERVICE CHARGE', 'ATM FEE'],
 'Client Payment': ['PAYMENT RECEIVED', 'INVOICE', 'DEPOSIT'],
 'Owner Draw': ['TRANSFER TO PERSONAL', 'OWNER WITHDRAWAL']}

In [27]:
for category, keywords in our_rules.items():
    #print(category)
    for i in keywords:
        mask = bank_transactions['description'].str.contains(i, case=False, na=False)
        uncategorized = bank_transactions['category'] == 'Uncategorized'
        bank_transactions.loc[mask & uncategorized, 'category'] = category
        bank_transactions.loc[mask & uncategorized, 'confidence'] = 0.9

In [28]:
bank_transactions

        date description  amount       category  confidence
0 2026-04-20         ABC     100  Uncategorized         0.0
1 2026-04-22         DEF    -100  Uncategorized         0.0

In [31]:
# Categorize by amount patterns
bank_transactions.loc[(bank_transactions['amount'] > 0) & (bank_transactions['category'] == 'Uncategorized'), 'category'] = 'Income'
bank_transactions.loc[(bank_transactions['amount'] < 0) & (bank_transactions['category'] == 'Uncategorized'), 'category'] = 'Other Expense'

In [32]:
bank_transactions

        date description  amount       category  confidence
0 2026-04-20         ABC     100         Income         0.0
1 2026-04-22         DEF    -100  Other Expense         0.0